# Site settings
title: Danilo Giordani
email: bestbug.corporation@gmail.com
url: https://www.danilogiordani.info
description: "Ciao sono un web developer e spero di aiutarti :)"

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: e67e22 
  secondary: d35400 
  secondary-dark: d35400 

# Footer settings
footer:
  copyright: Danilo Giordani
  location: Dove sono
  social: Around the Web
  credits: power by bestbug studio

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: key
    url: https://keybase.io/bestbug
  - title: skype
    url:  skype:bestbug_456
  - title: twitter
    url: https://twitter.com/Bestbug456
  - title: linkedin
    url: https://www.linkedin.com/profile/view?id=141450964&trk=nav_responsive_tab_profile_pic
  - title: github
    url: https://github.com/bestbug456/

# Postal address (add as many lines as necessary)
address:
  - line: Milano, Lombardia


# Credits content
credits: Questo sito è hostato da <a href="www.bestbugstudio.com">Bestbug studio</a>

# Build settings
markdown: kramdown
permalink: pretty